language: node_js

env:
  - YARN_GPG=no

stages:
  - test
  - build

node_js:
  - "8"

jobs:
  include:
    - stage: test
      os: linux
      name: "Lint/Test"
      script:
        - yarn lint
        - yarn test
    - os: osx
      name: "Lint/Test"
      script:
        - yarn lint
        - yarn test
    - os: windows
      name: "Lint/Test"
      script:
        - yarn lint
        - yarn test

    - stage: build
      name: "Build"
      os: linux
      script:
        - yarn build
