language: node_js

os:
  - linux
  - osx
  - windows

stages:
  - install
  - test
  - build

jobs:
  include:
    - stage: install
      script: yarn

    - stage: test
      script: yarn lint
      script: yarn test

    - stage: build
      script: yarn compile
