language: node_js

env:
  - YARN_GPG=no

stages:
  - test
  - build

node_js:
  - "8"

jobs:
  include:
    - stage: test
      os:
        - linux
        - osx
        - windows
      name: "Lint/Test"
      script:
        - yarn lint
        - yarn test

    - stage: build
      os: linux
      name: "Build"
      script:
        - yarn build
