language: node_js

env:
  - YARN_GPG=no

os:
  - linux
  - osx
  - windows

stages:
  - test
  - build

node_js:
  - "8"

jobs:
  include:
    - stage: test
      scripts:
        - yarn lint
        - yarn test

    - stage: build
      scripts:
        - yarn build
