language: node_js

os:
  - linux
  - osx
  - windows

stages:
  - install
  - test
  - build

node_js:
  - "8"

jobs:
  include:
    - stage: install
      scripts:
        - yarn

    - stage: test
      scripts:
        - yarn lint
        - yarn test

    - stage: build
      scripts:
        - yarn compile
