language: node_js

os:
  - linux
  - osx
  - windows

jobs:
  include:
    - stage: install
      script: yarn

    - stage: test
      script: yarn lint
      script: yarn test

    - stage: compile
      script: yarn compile
